{% set name = "pgrouting" %}
{% set version = "2.6.2" %}
{% set sha256 = "328fb46fbb865aecad9771b2892b06602fa796949a985b8973ce8bb09b469295" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pgrouting/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
  skip: True  # [win]


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cgal
    - cmake >= 3.2
    - perl
    - pkg-config
    - postgresql >= 9.3
    - postgis >= 2.2
    - cgal >= 4.2
  run:
    - postgresql >= 9.3
    - postgis >= 2.2
    - cgal >= 4.2

test:
  commands:
    - pgtap
    - pg_prove

about:
  home: http://github.com/pgrouting/pgrouting
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'pgRouting extends PostGIS/PostgreSQL geospatial database to provide geospatial routing and other network analysis functionality.'

  doc_url: https://docs.pgrouting.org
  dev_url: https://github.com/pgrouting/pgrouting

extra:
  recipe-maintainers:
    - sodre
